[versions]
agp = "8.9.1"
atomicfu = "0.32.1"
compose-bom = "2026.03.01"
compose-multiplatform = "1.10.3"
compose-navigation-mp = "2.9.0-beta01"
google-services = "4.4.4"
firebase-bom = "34.11.0"
hilt = "2.58"
kotest = "6.1.11"
kotlin = "2.3.21"
kotlinx-coroutines-core = "1.10.2"
kotlinx-datetime = "0.7.1"
ksp = "2.3.7"
lifecycle = "2.10.0"
lifecycle-viewmodel = "2.9.0"
sqlDelight = "2.3.2"
activityKtx = "1.13.0"
firebaseDatabaseKtx = "22.0.1"
credentials="1.5.0"
google-id = "1.2.0"
play-services-auth = "21.5.1"

[libraries]
# Android-specific Compose (using BOM)
activity-compose = { module = "androidx.activity:activity-compose" }
android-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
android-credentials-play-services = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials"  }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources" }
compose-navigation-mp = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation-mp" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
google-id = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "google-id" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel" }
material3 = { module = "androidx.compose.material3:material3" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }

# Compose Multiplatform (use compose.* notation in build files)
atomic-fu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

#DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.2.0" }

# Kotlin libraries
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Testing
io-kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

# Firebase
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx", version = "23.2.1" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-common = { module = "com.google.firebase:firebase-common-ktx", version = "21.0.0" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx", version = "25.1.4" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }

# SQLDelight
sql-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sql-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sql-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
